### ISSUE TITLE
Commiting and fetching consumer offsets in Kafka

### ISSUE THREAD

**Issue by mensfeld** [bpot/poseidon#118]
Are you planning to implement this one?

https://cwiki.apache.org/confluence/display/KAFKA/Committing+and+fetching+consumer+offsets+in+Kafka

**Comment by gerbal** [comment]
https://github.com/chingor13/poseidon/ Seems to have implemented this. We've forked the more active https://github.com/Tapjoy/poseidon with a test implementation of this feature at https://github.com/rightsup/poseidon

**Comment by mensfeld** [comment]
@gerbal  maybe it would be worth "retrieving" this gem from @bpot  as it seems he's no longer maintaining this one. Also I've noticed that this gem is strongly based on kafka-python that seems to be up 2 date with all Kafka changes.

**Comment by diegodurs** [comment]
@bpot is way behind both https://github.com/apptentive-engineering/poseidon and https://github.com/Tapjoy/poseidon

https://github.com/rightsup/poseidon seems to combines both goodness now and looks like a good start, what do you think?
Any suggestion on how to clean all this mess ?

**Comment by mensfeld** [comment]
@diegodurs yeah I was thinking about giving it a fresh start by rewriting kafka-python. It's not a big library and it is really well maintained - should not take a lot of time to make it as it should be. If it goes about poseidon it gets more and more behind Kafka

**Comment by RightsUpIO** [comment]
We'll love to follow you on this journey.
But regarding our needs, we'll try to make this feature works in @rightsup
Poseidon :)

Le mar. 26 janv. 2016 à 16:03, Maciej Mensfeld <notifications@github.com> a
écrit :

**Comment by mensfeld** [comment]
@RightsUpIO  thanks! I'm finishing some stuff for https://github.com/karafka/karafka (Kafka high leve Ruby framework) - which is strongly dependent of Poseidon and probably next week @nijikon and I will start working on that.

**Comment by gerbal** [comment]
Implementing consumer offsets in Poseidon requires implementing group management features and a bunch of newer Kafka features.

**Comment by mensfeld** [comment]
@gerbal that's why I'm against adding more stuff to Poseidon (based on how it is now) and building a better version of it.

**Comment by mensfeld** [comment]
Closing as anyhow it's unmaintained
