### ISSUE TITLE
send_messages should return false rather than raising an exception

### ISSUE THREAD

**Issue by hadronzoo** [bpot/poseidon#84]
Currently, `send_messages` [throws an error](https://github.com/bpot/poseidon/blob/b4dc2bec3c2c5b8957a821083602981b329f8bb6/lib/poseidon/sync_producer.rb#L66) when sending fails, rather than returning `false` [as documented in the API](http://www.rubydoc.info/gems/poseidon/Poseidon/Producer#send_messages-instance_method).

**Comment by bpot** [comment]
Error handling is far from ideal right now. I'm hesitant to change this behavior in case people are relying on the exception and not checking the return value. However, I will update the docs to clarify the behavior.

The 1.0 release (#21) will provide a much better API for handling errors.

**Comment by bpot** [comment]
Clarified https://github.com/bpot/poseidon/commit/dd74d9473692080cf49d3740eb3d7d929e79e1c9
